on:
  - push

jobs:
  build-and-test:
    env:
      DOTNET_INSTALL_DIR: .dotnet

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Restore Cached .NET Installation
        id: cache-dotnet
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DOTNET_INSTALL_DIR }}
          key: dotnet-${{ hashFiles('global.json') }}-take2

      - name: Set environment for .NET
        if: steps.cache-dotnet.outputs.cache-hit == 'true'
        run: echo ${{ env.DOTNET_INSTALL_DIR }} >> ${{ env.GITHUB_PATH }}

      - name: Install .NET
        if: steps.cache-dotnet.outputs.cache-hit != 'true'
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Cache .NET Installation
        if: steps.cache-dotnet.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.DOTNET_INSTALL_DIR }}
          key: dotnet-${{ hashFiles('global.json') }}-take2

      - name: Build
        run: dotnet build -c Release

      - name: Run tests
        run: dotnet test -c Release --no-build --logger 'console;verbosity=normal' --logger trx --results-directory=TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v3 # https://code.forgejo.org/forgejo/runner/issues/144
        with:
          name: dotnet-results
          path: TestResults
        if: ${{ always() }}
