on: [push]
jobs:
  test:
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build -c Release

      - name: Run Tests
        run: dotnet test -c Release
