on:
  push:
    branches:
      - main
      - '0.5'

jobs:
  build-and-test:
    runs-on: docker
    container:
      image: airbreather/dotnet-sdk-9.0-forgejo-runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Restore cached packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore --locked-mode

      - name: Build
        shell: bash
        run: |
          pids=()
          dotnet format --no-restore --verify-no-changes & pids+=($!)
          dotnet build --no-restore -c Release & pids+=($!)
          dotnet publish src/Autopelago/Autopelago.csproj --no-restore -c Release -r win-x64 -o dist/Autopelago_win-x64 & pids+=($!)
          dotnet publish src/Autopelago/Autopelago.csproj --no-restore -c Release -r linux-x64 -o dist/Autopelago_linux-x64 & pids+=($!)
          dotnet publish src/Autopelago/Autopelago.csproj --no-restore -c Release -r osx-x64 -o dist/Autopelago_osx-x64 & pids+=($!)
          failure=false
          for pid in ${pids[*]}; do
              if ! wait $pid; then
                failure=true
              fi
          done
          if $failure; then
            exit 1
          fi

      - name: Run tests
        run: dotnet test -c Release --no-build --logger 'console;verbosity=detailed' --logger trx --results-directory=TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-test-results
          path: TestResults
        if: always()

      - name: Prepare release directory
        shell: bash
        run: |
          pushd dist;
          mkdir release;
          shopt -s dotglob
          pids=()
          (cd Autopelago_win-x64; zip -9 -r ../release/Autopelago_win-x64.zip *) & pids+=($!)
          (cd Autopelago_linux-x64; tar -cf - * | zstd --ultra -22 -T0 -o ../release/Autopelago_linux-x64.tar.zst) & pids+=($!)
          echo "RELEASE_NUMBER=$(date -u +%Y%m%d%H%M%S)" >> "$GITHUB_ENV";
          failure=false
          for pid in ${pids[*]}; do
              if ! wait $pid; then
                failure=true
              fi
          done
          if $failure; then
            exit 1
          fi
          popd;

      - name: Release
        uses: actions/forgejo-release@v2
        with:
          tag: 'Autopelago_${{ env.RELEASE_NUMBER }}'
          token: ${{ secrets.RELEASE_PAT }}
          release-dir: dist/release
          direction: upload
          verbose: true
          override: true
          prerelease: true
