on:
  push:
    branches:
      - avalonia-wip

jobs:
  build-and-test:
    runs-on: docker
    container:
      image: airbreather/dotnet-sdk-8.0-forgejo-runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Restore cached packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore --locked-mode

      - name: Build
        shell: bash
        run: |
          dotnet build -c Release --no-restore &
          dotnet publish src/Autopelago/Autopelago.csproj --no-restore -c Release -r win-x64 -o dist/Autopelago_win-x64 &
          dotnet publish src/Autopelago/Autopelago.csproj --no-restore -c Release -r linux-x64 -o dist/Autopelago_linux-x64 &
          wait < <(jobs -p);

      - name: Run tests
        run: dotnet test -c Release --no-build --logger 'console;verbosity=detailed' --logger trx --results-directory=TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-test-results
          path: TestResults
        if: always()

      - name: Prepare release directory
        shell: bash
        run: |
          mkdir dist;
          pushd artifacts;
          zip -9 -r ../dist/Autopelago_win-x64.zip Autopelago_win-x64 &
          tar -cf - Autopelago_linux-x64 | zstd --ultra -22 -T0 -o ../dist/Autopelago_linux-x64.tar.zst &
          echo "RELEASE_NUMBER=$(date -u +%Y%m%d%H%M%S)" >> "$GITHUB_ENV";
          wait < <(jobs -p);
          popd;

      - name: Release
        uses: actions/forgejo-release@v2
        with:
          tag: 'Autopelago_${{ env.RELEASE_NUMBER }}'
          token: ${{ secrets.RELEASE_PAT }}
          release-dir: dist
          direction: upload
          verbose: true
          override: true
          prerelease: true
