on:
  - push

jobs:
  build-and-test:
    container:
      image: airbreather/dotnet-sdk-8.0-forgejo-runner

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Build
        run: dotnet build -c Release

      - name: Run tests
        run: dotnet test -c Release --no-build --logger 'console;verbosity=normal' --logger trx --results-directory=TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v3 # https://code.forgejo.org/forgejo/runner/issues/144
        with:
          name: dotnet-results
          path: TestResults
        if: ${{ always() }}
