on: [push]
jobs:
  test:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet build -c Release
      - run: dotnet publish -c Release tests/Autopelago.Test/Autopelago.Test.csproj -o publish/Autopelago.Test/
      - run: ./Autopelago.Test
        working-directory: publish/Autopelago.Test
