on:
  - push

jobs:
  build-and-test:
    container:
      image: airbreather/dotnet-sdk-8.0-forgejo-runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Restore cached packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Run tests
        run: dotnet test -c Release --no-build --logger 'console;verbosity=detailed' --logger trx --results-directory=TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-test-results
          path: TestResults
        if: always()

      - name: Publish (win-x64)
        run: dotnet publish src/Autopelago/Autopelago.csproj -c Release -r win-x64 -o artifacts/win-x64

      - name: Upload (win-x64)
        uses: actions/upload-artifact@v3
        with:
          name: win-x64
          path: artifacts/win-x64

      - name: Publish (linux-x64)
        run: dotnet publish src/Autopelago/Autopelago.csproj -c Release -r linux-x64 -o artifacts/linux-x64

      - name: Upload (linux-x64)
        uses: actions/upload-artifact@v3
        with:
          name: linux-x64
          path: artifacts/linux-x64
