public enum Region
{
    Traveling,
    BeforeBasketball,
    Basketball,
    BeforeMinotaur,
    BeforePrawnStars,
    Minotaur,
    PrawnStars,
    BeforeRestaurant,
    BeforePirateBakeSale,
    Restaurant,
    PirateBakeSale,
    AfterRestaurant,
    AfterPirateBakeSale,
    BowlingBallDoor,
    Goldfish,
    CompletedGoal,
}
