server: "foo.example.com"
port: 55555

defaultSettings:
  minSecondsPerGameStep: 60
  maxSecondsPerGameStep: 90
  movementSpeedMultiplier: 1

slots:
  - name: "Rat King"
    # uncomment this line and fill it in, if you have a password:
    # password: "Some Password"

    # you can override things from "defaultSettings" here
    # anything you don't override will use the defaults
    overriddenSettings:
      movementSpeedMultiplier: 1.5

  - name: "Normal Rat 1"
    # uncomment this line and fill it in, if you have a password:
    # password: "Some Password"

    # you can override things from "defaultSettings" here
    # anything you don't override will use the defaults
    overriddenSettings:
      movementSpeedMultiplier: 0.8

  - name: "Normal Rat 2"
    # uncomment this line and fill it in, if you have a password:
    # password: "Some Password"

    # you can also skip "overriddenSettings" entirely.

  - name: "Normal Rat 3"
    # uncomment this line and fill it in, if you have a password:
    # password: "Some Password"
