FROM airbreather/forgejo-runner

RUN wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
  && dpkg -i packages-microsoft-prod.deb \
  && rm packages-microsoft-prod.deb \
  && apt-get update \
  && apt-get install -y dotnet-sdk-9.0 \
  && rm -rf /var/lib/apt/lists/* \
  # Trigger first run experience by running arbitrary cmd
  && dotnet help
