on:
  push:
    branches:
      - main
      - aot

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore --locked-mode

      - name: Build
        run: |
          dotnet format --no-restore --verify-no-changes & pids+=($!)
          dotnet build --no-restore -c Release & pids+=($!)
          failure=false
          for pid in ${pids[*]}; do
              if ! wait $pid; then
                failure=true
              fi
          done
          if $failure; then
            exit 1
          fi

      - name: Run tests
        run: dotnet run -c Release --no-build --project tests/**/*.csproj -- --output Detailed --report-trx --results-directory TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults
        if: always()

  publish:
    strategy:
      matrix:
        os:
          - runner: ubuntu-latest
            rid: linux-x64

          - runner: windows-latest
            rid: win-x64

    runs-on: ${{ matrix.os.runner }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore --locked-mode

      - name: Publish
        run: dotnet publish src/Autopelago/Autopelago.csproj --no-restore -c Release -r ${{ matrix.os.rid }} -o dist/release

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.rid }}
          path: dist/release/**
          if-no-files-found: 'error'
          include-hidden-files: 'true' # if we made any, then they'd be needed.
