name: Publish

on:
  push:
  release:
    types:
      - published

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get Bun
        uses: oven-sh/setup-bun@v2

      - name: Install packages
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Run tests
        run: bun run test

      - name: Build
        run: bun run release

      - name: Create release zip
        run: zip -r dist.zip dist/

      - name: Upload to workflow artifact
        uses: actions/upload-artifact@v7
        with:
          path: dist.zip
          archive: false

      - if: ${{ github.event_name == 'release' }}
        name: Upload to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist.zip

      - if: ${{ github.event_name == 'release' }}
        name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - if: ${{ github.event_name == 'release' }}
        name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

      - if: ${{ github.event_name == 'release' }}
        name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
